# Generated by Django 4.1 on 2023-09-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoffeeShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("alamat", models.CharField(max_length=255)),
                ("harga_makanan", models.IntegerField()),
                ("harga_minuman", models.IntegerField()),
                ("deskripsi", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Fasilitas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wifi", models.BooleanField(default=False)),
                ("mushola", models.BooleanField(default=False)),
                ("ruang_lesehan", models.BooleanField(default=False)),
                ("ruang_ac", models.BooleanField(default=False)),
                ("halaman_parkir", models.BooleanField(default=False)),
                ("live_music", models.BooleanField(default=False)),
                ("games", models.BooleanField(default=False)),
                ("kabel_terminal", models.BooleanField(default=False)),
                ("toilet", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Jarak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=12)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=12)),
            ],
        ),
    ]
