# Generated by Django 4.1 on 2023-09-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skripsi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fasilitas",
            name="games",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="fasilitas",
            name="halaman_parkir",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="fasilitas",
            name="kabel_terminal",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="fasilitas",
            name="live_music",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="fasilitas",
            name="mushola",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="fasilitas",
            name="ruang_ac",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="fasilitas",
            name="ruang_lesehan",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="fasilitas",
            name="toilet",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="fasilitas",
            name="wifi",
            field=models.CharField(max_length=5),
        ),
    ]
