# Generated by Django 4.1 on 2023-09-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "skripsi",
            "0002_alter_fasilitas_games_alter_fasilitas_halaman_parkir_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="coffeeshop",
            name="gambar",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
