# Generated by Django 4.1 on 2023-09-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skripsi", "0003_coffeeshop_gambar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffeeshop",
            name="gambar",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
