# Generated by Django 4.1 on 2023-09-11 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skripsi", "0004_alter_coffeeshop_gambar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fasilitas",
            name="games",
        ),
        migrations.RemoveField(
            model_name="fasilitas",
            name="halaman_parkir",
        ),
        migrations.RemoveField(
            model_name="fasilitas",
            name="kabel_terminal",
        ),
        migrations.RemoveField(
            model_name="fasilitas",
            name="live_music",
        ),
        migrations.RemoveField(
            model_name="fasilitas",
            name="ruang_ac",
        ),
        migrations.RemoveField(
            model_name="fasilitas",
            name="ruang_lesehan",
        ),
        migrations.RemoveField(
            model_name="fasilitas",
            name="toilet",
        ),
    ]
