# Generated by Django 4.1 on 2023-09-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skripsi", "0005_remove_fasilitas_games_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fasilitas",
            name="halaman_parkir",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="fasilitas",
            name="hiburan",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="fasilitas",
            name="kabel_terminal",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="fasilitas",
            name="live_music",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="fasilitas",
            name="ruang_ac",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="fasilitas",
            name="ruang_lesehan",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="fasilitas",
            name="toilet",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
