# Generated by Django 4.1 on 2023-09-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skripsi", "0007_riwayat"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Fasilitas",
        ),
        migrations.DeleteModel(
            name="Jarak",
        ),
        migrations.AddField(
            model_name="coffeeshop",
            name="halaman_parkir",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="coffeeshop",
            name="hiburan",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="coffeeshop",
            name="kabel_terminal",
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="coffeeshop",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="coffeeshop",
            name="live_music",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="coffeeshop",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="coffeeshop",
            name="mushola",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="coffeeshop",
            name="ruang_ac",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="coffeeshop",
            name="ruang_lesehan",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="coffeeshop",
            name="toilet",
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="coffeeshop",
            name="wifi",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
